import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatDate(date: Date | string | number, timeZone: string = "Asia/Kolkata") {
  if (!date) return "";
  const d = typeof date === "string" ? new Date(date) : date;
  return new Intl.DateTimeFormat("en-IN", {
    timeZone,
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(d);
}

/** Formats a date/time value into local clinic time (e.g., "12:30 PM"). */
export function formatClinicTime(date: Date | string | number, timeZone: string = "Asia/Kolkata") {
  if (!date) return "";
  const d = typeof date === "string" ? new Date(date) : date;
  return new Intl.DateTimeFormat("en-IN", {
    timeZone,
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  }).format(d);
}

export function formatTime(date: Date | string | number, timeZone: string = "Asia/Kolkata") {
  return formatClinicTime(date, timeZone);
}

export function getLocalDateString(date: Date | string = new Date(), timeZone: string = "Asia/Kolkata"): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).format(d);
}

/** Formats a doctor display name cleanly with proper Dr. prefix */
export function formatDoctorDisplayName(rawName?: string): string {
  if (!rawName || rawName.trim() === "" || rawName.toLowerCase() === "doctor") {
    return "the Doctor";
  }
  let clean = rawName.trim();
  while (/^(dr\.?|doctor)\s+/i.test(clean)) {
    clean = clean.replace(/^(dr\.?|doctor)\s+/i, "").trim();
  }
  return clean ? `Dr. ${clean}` : "the Doctor";
}

/**
 * Strips emojis, pictographs, decorative symbols, and control characters from person names.
 * Ensures clean professional clinical display (e.g. "Dharmender Kumar 😂😂" -> "Dharmender Kumar").
 */
export function sanitizePersonName(rawName?: string | null): string {
  if (!rawName) return "";
  const cleaned = rawName
    // Strip emojis, pictographs, symbols (like 😂, 🙏, 🌸, ⚡, etc.)
    .replace(/[\p{Extended_Pictographic}\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}]/gu, '')
    // Strip unwanted decorative punctuation (like ~~~, ***, ---)
    .replace(/[~*_#^<>|\\/{}\[\]]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned;
}

/**
 * Detects if an incoming message is an automated template, emergency notice echo,
 * or booking confirmation card generated by Gyrex/Docflo or WhatsApp bots.
 * Used to prevent infinite recursive bot-to-bot ping pong loops.
 */
export function isBotTemplateEcho(text?: string | null): boolean {
  if (!text || typeof text !== "string") return false;
  const t = text.trim();
  if (t.length === 0) return false;

  // 1. Emergency notices & alerts generated by our triage system
  if (/⚠️\s*\*.*?(?:emergency|surgical|pediatric).*?(?:notice|alert)\*/i.test(t)) return true;
  if (/If the patient is in critical condition or experiencing an acute emergency/i.test(t)) return true;
  if (/please visit the nearest hospital emergency room immediately/i.test(t)) return true;
  if (/proceed immediately to the nearest.*emergency.*department/i.test(t)) return true;

  // 2. Appointment & Schedule system headers
  if (/\*(?:APPOINTMENT\s+CONFIRMED|APPOINTMENT\s+RESCHEDULED|OPD\s+TIMING\s+UPDATE|IMPORTANT\s+CLINIC\s+NOTICE|TASK\s+COMPLETED|PATIENT\s+APPOINTMENT\s+CANCELLED)\*/i.test(t)) return true;
  if (/\b(?:Consultation Fee|Appointment Date|Appointment Time|Clinic Location|Clinic OPD Hours|Drive safely! 🚗)\b/i.test(t) && /Doctor:|Patient:|Slot:/i.test(t)) return true;

  // 3. Receptionist bot self-introductions and automated sign-offs
  if (/\b(?:virtual\s+receptionist\s+for|the\s+virtual\s+receptionist|i\s+assist\s+with\s+appointment\s+bookings,\s+clinic\s+timings)\b/i.test(t)) return true;
  if (/\b(?:ki\s+taraf\s+se\s+aap\s+sabhi\s+ko\s+shubh\s+sandhya|have\s+a\s+wonderful\s+evening!\s*🙏😊|unka\s+swagat\s+karne\s+ke\s+liye\s+clinic\s+team\s+bilkul\s+ready\s+hai)\b/i.test(t)) return true;

  return false;
}


