import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSessionData } from "@/lib/session";
import { runSeoEngine } from "@/lib/seo-engine/engine";

export async function GET(req: NextRequest) {
  try {
    let session;
    try {
      session = await getSessionData();
    } catch (e) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    if (!session || !session.doctorId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const activeAccount = await prisma.gbpAccount.findFirst({
      where: { doctorId: session.doctorId },
      orderBy: { createdAt: "desc" },
    });

    if (!activeAccount) {
      return NextResponse.json({ tasks: [], healthScore: null });
    }

    // Check if we have a successful EngineRun for today
    const startOfDay = new Date();
    startOfDay.setHours(0, 0, 0, 0);

    const latestRun = await prisma.engineRun.findFirst({
      where: {
        gbpAccountId: activeAccount.id,
        status: "SUCCESS",
        startedAt: { gte: startOfDay }
      }
    });

    // Generate daily idempotency key
    const idempotencyKey = `daily-scan-${startOfDay.toISOString().split('T')[0]}`;

    if (!latestRun) {
      // Safely executes exactly once per day thanks to unique constraint
      await runSeoEngine(activeAccount.id, idempotencyKey);
    }

    // Fetch pending tasks generated by the engine
    const tasks = await prisma.seoTask.findMany({
      where: { 
        gbpAccountId: activeAccount.id,
        status: "PENDING"
      },
      orderBy: { createdAt: "desc" }
    });

    // Health score calculated natively from confidence and severity
    let healthScore = 100;
    for (const t of tasks) {
      if (t.priority === "CRITICAL") healthScore -= 20;
      else if (t.priority === "HIGH") healthScore -= 10;
      else if (t.priority === "MEDIUM") healthScore -= 5;
      else if (t.priority === "LOW") healthScore -= 2;
    }
    
    healthScore = Math.max(0, Math.min(100, healthScore));

    return NextResponse.json({ tasks, healthScore });
  } catch (error) {
    console.error("GET /api/gbp/tasks Error:", error);
    return NextResponse.json(
      { error: "Failed to fetch tasks" },
      { status: 500 }
    );
  }
}
