import { prisma } from "@/lib/prisma";

export class LocalSeoService {
  /**
   * Section 1: Google Health Overview
   * Returns a qualitative summary of the location's Google presence.
   */
  static async getOverview(locationId: string, doctorId: string) {
    const account = await prisma.gbpAccount.findFirst({
      where: { id: locationId, doctorId }
    });

    if (!account) return null;

    const insights = account.insightsData as any || {};
    const reviewCount = insights.user_ratings_total || 0;
    const rating = insights.rating || 0;
    
    // Determine qualitative status
    let status = "Needs Attention";
    let statusReason = "Connect your Google Business Profile to see your live metrics";
    let statusColor = "amber";

    if (account.accessToken) {
      if (reviewCount > 100 && rating >= 4.5) {
        status = "Excellent";
        statusReason = "Strong review profile driving conversions";
        statusColor = "emerald";
      } else if (reviewCount > 20 && rating >= 4.0) {
        status = "Good";
        statusReason = "Solid presence, but room to grow reviews";
        statusColor = "blue";
      } else if (reviewCount === 0) {
        status = "Critical";
        statusReason = "Zero reviews detected. Start requesting reviews immediately.";
        statusColor = "red";
      } else {
        status = "Needs Attention";
        statusReason = "Review score below 4.0 or low volume.";
        statusColor = "amber";
      }
    }

    return {
      businessName: insights.locationName || account.locationName || "Unknown Business",
      primaryCategory: insights.categories?.primaryCategory?.displayName || "Medical Clinic",
      rating,
      reviewCount,
      calls: insights.phoneCalls || 0,
      views: insights.totalViews || 0,
      directionRequests: insights.directionRequests || 0,
      websiteClicks: insights.websiteClicks || 0,
      connectionStatus: account.accessToken ? "Connected" : "Disconnected",
      lastSync: account.updatedAt,
      qualitativeStatus: {
        label: status,
        reason: statusReason,
        color: statusColor
      }
    };
  }

  /**
   * Section 2: Action Center
   * Returns PENDING tasks generated by the SEO Engine.
   */
  static async getActionCenter(locationId: string, doctorId: string) {
    const account = await prisma.gbpAccount.findFirst({
      where: { id: locationId, doctorId }
    });

    if (!account) return [];

    const latestProfileSnapshot = await prisma.profileSnapshot.findFirst({
      where: { gbpAccountId: account.id },
      orderBy: { date: "desc" }
    });

    if (!latestProfileSnapshot) return [];

    const snapshotJson = latestProfileSnapshot.json as Record<string, unknown>;
    const recommendations = (snapshotJson.recommendations as any[]) || [];
    return recommendations.map((rec, index) => ({
      id: rec.id || `rec_${index}`,
      title: rec.recommendation || rec.title || "Recommendation",
      priority: rec.priority || "MEDIUM",
      reason: rec.evidence || rec.reason || "",
      expectedImpact: rec.expectedImpact || "",
      estimatedEffort: "Low",
      source: "Google Profile API",
      confidence: "High"
    }));
  }

  /**
   * Section 3: Search Visibility
   * Returns official GBP metrics and historical trends.
   */
  static async getVisibilityMetrics(locationId: string, doctorId: string) {
    const account = await prisma.gbpAccount.findFirst({
      where: { id: locationId, doctorId }
    });

    if (!account) return null;

    const insights = account.insightsData as any || {};

    return {
      profileViews: insights.totalViews || 0,
      phoneCalls: insights.phoneCalls || 0,
      directionRequests: insights.directionRequests || 0,
      websiteClicks: insights.websiteClicks || 0,
      discoverySearches: insights.discoverySearches || 0,
      directSearches: insights.directSearches || 0,
      brandedSearches: insights.brandedSearches || 0,
      trends: {
        viewsChange: insights.viewsChange || null,
        searchChange: insights.searchChange || null,
        actionsChange: insights.actionsChange || null
      }
    };
  }

  /**
   * Section 5: Profile Health
   * Concrete completeness checklist based on GBP fields.
   */
  static async getProfileHealth(locationId: string, doctorId: string) {
    const account = await prisma.gbpAccount.findFirst({
      where: { id: locationId, doctorId }
    });

    if (!account) return null;

    const latestProfileSnapshot = await prisma.profileSnapshot.findFirst({
      where: { gbpAccountId: account.id },
      orderBy: { date: "desc" }
    });

    if (!latestProfileSnapshot) return null;

    const profile = latestProfileSnapshot.json as any || {};

    const checkField = (value: any) => {
      if (value === null || value === undefined) return "Missing";
      if (Array.isArray(value) && value.length === 0) return "Missing";
      if (typeof value === "string" && value.trim() === "") return "Missing";
      return "Complete";
    };

    return {
      businessName: checkField(profile.name),
      primaryCategory: checkField(profile.primaryCategory),
      secondaryCategories: checkField(profile.categories),
      description: checkField(profile.description),
      hours: checkField(profile.hours),
      phone: checkField(profile.phone),
      website: checkField(profile.website),
      photos: profile.hasPhotos ? "Complete" : "Missing",
      attributes: checkField(profile.attributes),
      posts: "Missing" // Wait for Phase 6 (Posts)
    };
  }

  /**
   * System Health Component
   * Engine status and API connectivity.
   */
  static async getSystemHealth(locationId: string, doctorId: string) {
    const account = await prisma.gbpAccount.findFirst({
      where: { id: locationId, doctorId }
    });

    if (!account) return null;

    const latestSnapshot = await prisma.gbpPerformanceSnapshot.findFirst({
      where: { gbpAccountId: account.id },
      orderBy: { date: "desc" }
    });

    return {
      googleConnected: !!account.accessToken,
      lastGbpSync: account.updatedAt,
      scanStatus: latestSnapshot ? "SUCCESS" : "NEVER_RUN",
      lastAnalysis: latestSnapshot ? latestSnapshot.date : null,
      searchConsoleConnected: false,
      placesConnected: false
    };
  }
}
