export function exportReportToCSV(reportData: any) {
  if (!reportData || !reportData.metadata) {
    alert("Report data is missing or incomplete.");
    return;
  }

  const { metadata, dateRange } = reportData;

  const rows = [];
  
  // Header Metadata
  rows.push(["Clinic Name", metadata.clinicName]);
  rows.push(["Report Name", metadata.reportName]);
  rows.push(["Generated By", metadata.generatedBy]);
  rows.push(["Generated On", metadata.generatedOn]);
  rows.push(["Timezone", metadata.timezone]);
  rows.push(["Date Range", `${dateRange.startDate} to ${dateRange.endDate}`]);
  rows.push([]); // Empty row separator
  
  // Data Sections
  rows.push(["Category", "Metric", "Value"]);

  // Patients
  rows.push(["Patients", "Total New Patients", reportData.totalNewPatients]);
  if (reportData.patientFunnel) {
    rows.push(["Patients", "Leads", reportData.patientFunnel.leads]);
    rows.push(["Patients", "Active", reportData.patientFunnel.active]);
    rows.push(["Patients", "Inactive", reportData.patientFunnel.inactive]);
    rows.push(["Patients", "Lost", reportData.patientFunnel.lost]);
  }
  
  // Appointments
  rows.push(["Appointments", "Total Appointments", reportData.totalAppointments]);
  if (reportData.appointmentOutcomes) {
    rows.push(["Appointments", "Scheduled", reportData.appointmentOutcomes.scheduled]);
    rows.push(["Appointments", "Completed", reportData.appointmentOutcomes.completed]);
    rows.push(["Appointments", "Cancelled", reportData.appointmentOutcomes.cancelled]);
    rows.push(["Appointments", "No Show", reportData.appointmentOutcomes.noShow]);
  }

  // Communications
  rows.push(["Communications", "Total Messages", reportData.totalMessages]);
  rows.push(["Communications", "Incoming Messages", reportData.incomingMessages]);
  rows.push(["Communications", "Outgoing Messages", reportData.outgoingMessages]);
  rows.push(["Communications", "AI Handled", reportData.aiHandledMessages]);
  rows.push(["Communications", "Estimated AI Hours Saved", reportData.aiHoursSaved]);
  rows.push(["Communications", "Review Requests Sent", reportData.reviewRequestsSent]);

  // Reputation
  rows.push(["Reputation", "Review Count", reportData.reviewCount]);
  rows.push(["Reputation", "Average Rating", reportData.avgRating ? Number(reportData.avgRating).toFixed(1) : "N/A"]);

  if (reportData.gbpData) {
    rows.push(["GBP", "Total Views", reportData.gbpData.totalViews]);
    rows.push(["GBP", "Total Searches", reportData.gbpData.totalSearches]);
    rows.push(["GBP", "Phone Calls", reportData.gbpData.phoneCalls]);
  }

  // Build CSV content string
  const csvContent = rows.map(row => 
    row.map(cell => {
      if (cell === null || cell === undefined) return '""';
      const cellStr = String(cell);
      // Escape quotes and wrap in quotes if there's a comma
      if (cellStr.includes(",") || cellStr.includes('"')) {
        return `"${cellStr.replace(/"/g, '""')}"`;
      }
      return cellStr;
    }).join(",")
  ).join("\n");

  // Trigger download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `Report_${metadata.clinicName.replace(/ /g, "_")}_${dateRange.startDate}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
